### PR TITLE
Fixing broken link

### LINKED ISSUE #121: Broken link in ReadMe.md
Clicking on the link for pandora-web in the ReadMe results in a 404

### PR DESCRIPTION
**Pull request by JonnyMc94**
Fixed the pandora-web doc link in the Readme.md. 

Fixes #121

### CODE REVIEW

**Comment by WJ-van-Hoek** [comment]
I appreciate your PR very much. Documentation is very far behind, actually non-existent....

I added this tag for my own understanding of adding such these things to the repo. Work needs to be done on doc in a later stage.

**Comment by JonnyMc94** [comment]
@WJ-van-Hoek Cool, no worries! I think it's a very interesting project and would like to continue contributing. If you could mention any other good first issues I can have a look while I get to grips with the codebase

**Comment by WJ-van-Hoek** [comment]
@JonnyMc94 Appreciated! I don't know your level in Java and the Spring ecosystem? If you have some good knowledge I could prepare some tickets that could be useful and interesting at the same time. Otherwise I strongly suggest to do a Spring course first.

If you are willing to contribute to the actual content of what I am building I definitely need to come up with some clear issues, as the ones in the list are solely made by me and for me. Also I will write a more extensive readme.md that elaborates on the purpose of the whole thing.

The state of the application at this moment is basically only a bunch of components that work together. Documentation is basically non-existing, code coverage is declining and I need to fix a lot checkstyle stuff. There is not a user-friendly interface and no functional input, but I am slowly working towards that. I mostly work on this on Fridays and some weekends, so if I don't respond during the week, it is because of that.

**Comment by JonnyMc94** [comment]
@WJ-van-Hoek I have good experience with Java (professionally for the last few years) and have recently started working with Spring. I know a lot of the basics and I'm continuing to learn so would be willing to work on some tickets for sure! 

A more extensive Readme would be beneficial for sure but I would be willing to contribute to the project as a whole!

**Pull request merged**
